// services/taskGenerator.js
import { GoogleGenerativeAI } from "@google/generative-ai";

const genAI = new GoogleGenerativeAI(process.env.GOOGLE_GENAI_API_KEY);
const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });

// Shared JSON parsing helper
const parseLLMJsonResponse = (text) => {
  // Look for the start of the JSON object or array
  let jsonStart = text.indexOf('{');
  const arrayStart = text.indexOf('[');

  if (jsonStart === -1 || (arrayStart !== -1 && arrayStart < jsonStart)) {
    jsonStart = arrayStart;
  }

  if (jsonStart === -1) {
    throw new Error('No JSON object/array found in response');
  }

  // Look for the end of the JSON object or array
  let jsonEnd = -1;
  if (text.charAt(jsonStart) === '{') {
    jsonEnd = text.lastIndexOf('}');
  } else if (text.charAt(jsonStart) === '[') {
    jsonEnd = text.lastIndexOf(']');
  }
  
  if (jsonEnd === -1 || jsonEnd < jsonStart) {
    throw new Error('Valid JSON object/array end not found in response');
  }

  const jsonString = text.slice(jsonStart, jsonEnd + 1);
  
  // Clean the string of any control characters before parsing
  const cleanJsonString = jsonString.replace(/[\x00-\x1F\x7F-\x9F]/g, '');
  
  return JSON.parse(cleanJsonString);
};

const parseLLMTasksResponse = (text) => {
  const data = parseLLMJsonResponse(text);
  if (!data.tasks || !Array.isArray(data.tasks)) {
    throw new Error('Tasks array missing or invalid in LLM response');
  }
  return data.tasks;
};

export const generateProjectIdea = async (skills, interests) => {
  // Format skills and interests for the prompt
  const skillsString = JSON.stringify(skills);
  const interestsString = JSON.stringify(interests);

  const prompt = `
Context Parameters Provided:

Skills: ${skillsString}
Interests: ${interestsString}

Instructions for AI Generation:

"Using the provided skills and interests, generate a unique project name that reflects this synergy. Then create a descriptive project plan whose scope utilizes those skills towards advancing those interests as much as possible. Try to limit the scope to mostly needing only the skills the user has listed. Format your response as JSON with keys Name and Description."
`;

  try {
    console.log("Generating project idea with prompt:", prompt);
    const result = await model.generateContent(prompt);
    const responseText = result.response.text();
    console.log("LLM response for project idea:", responseText);

    // Parse the JSON response
    const projectIdea = parseLLMJsonResponse(responseText);
    
    if (!projectIdea.Name || !projectIdea.Description) {
      throw new Error('LLM response missing Name or Description for project idea.');
    }

    return projectIdea; // Should be { Name: "...", Description: "..." }
  } catch (error) {
    console.error('Error generating project idea:', error);
    throw new Error(`Failed to generate project idea: ${error.message}`);
  }
};

export const autoGenerateSubtasks = async (tasks,projectName, projectDescription, tags, creator_id) => {
  const formattedTasks = tasks.map((task, index) => {
    return `Task ${index + 1}:
Name: ${task.name}
Description: ${task.description}
Related Skill ID: ${task.skill_id || 'None'}`
  }).join('\n\n');

  const prompt = `
You are an expert project manager and task engineer. Your job is to break complex tasks into smaller, manageable subtasks that can be independently assigned.

For each task below, return a **JSON array** of objects like this format:
[
  {
    "name": "Subtask name",
    "description": "Brief description",
    "skill_id": "Optional related skill ID or null",
    "dependencies": [Optional array of subtask names this subtask depends on]
  },
  ...
]

Tasks to granularize:

${formattedTasks}

Here are the rules:
- All IDs (project IDs, task IDs) must be **unique, sequential integers starting at 1**.
- Maintain **relationships**: 
  - "project_id" in tasks must match the corresponding project's new ID.
  - "skill_id" in tasks must match the correct skill's existing ID.
  - "dependencies" in tasks must reference the correct **new task IDs**.
- Output data in **JSON format**, with **one array per table** (projects, tasks).

Here is the **Skills List** with assigned IDs:
json
[
  { "id": 1, "name": "Project management" },
  { "id": 2, "name": "Time management" },
  { "id": 3, "name": "Leadership" },
  { "id": 4, "name": "Public speaking" },
  { "id": 5, "name": "Problem-solving" },
  { "id": 6, "name": "Critical thinking" },
  { "id": 7, "name": "Teamwork" },
  { "id": 8, "name": "Research" },
  { "id": 9, "name": "Data analysis" },
  { "id": 10, "name": "Programming" },
  { "id": 11, "name": "Writing" },
  { "id": 12, "name": "Creative writing" },
  { "id": 13, "name": "Technical writing" },
  { "id": 14, "name": "Design" },
  { "id": 15, "name": "Graphic design" },
  { "id": 16, "name": "Web development" },
  { "id": 17, "name": "UX/UI design" },
  { "id": 18, "name": "Digital marketing" },
  { "id": 19, "name": "SEO" },
  { "id": 20, "name": "Social media management" },
  { "id": 21, "name": "Email marketing" },
  { "id": 22, "name": "Event planning" },
  { "id": 23, "name": "Conflict resolution" },
  { "id": 24, "name": "Customer service" },
  { "id": 25, "name": "Sales" },
  { "id": 26, "name": "Negotiation" },
  { "id": 27, "name": "Marketing strategy" },
  { "id": 28, "name": "Branding" },
  { "id": 29, "name": "Photography" },
  { "id": 30, "name": "Videography" },
  { "id": 31, "name": "Film editing" },
  { "id": 32, "name": "Animation" },
  { "id": 33, "name": "3D modeling" },
  { "id": 34, "name": "App development" },
  { "id": 35, "name": "Mobile web development" },
  { "id": 36, "name": "Database management" },
  { "id": 37, "name": "Machine learning" },
  { "id": 38, "name": "Artificial intelligence" },
  { "id": 39, "name": "Networking" },
  { "id": 40, "name": "Cybersecurity" },
  { "id": 41, "name": "Cloud computing" },
  { "id": 42, "name": "Graphic design software" },
  { "id": 43, "name": "Microsoft Office Suite" },
  { "id": 44, "name": "Excel" },
  { "id": 45, "name": "PowerPoint" },
  { "id": 46, "name": "Photoshop" },
  { "id": 47, "name": "Illustrator" },
  { "id": 48, "name": "Final Cut Pro" },
  { "id": 49, "name": "AutoCAD" },
  { "id": 50, "name": "Sketch" },
  { "id": 51, "name": "Figma" },
  { "id": 52, "name": "InDesign" },
  { "id": 53, "name": "Video production" },
  { "id": 54, "name": "Audio production" },
  { "id": 55, "name": "Editing" },
  { "id": 56, "name": "Public relations" },
  { "id": 57, "name": "Foreign languages" },
  { "id": 58, "name": "Translation" },
  { "id": 59, "name": "Copywriting" },
  { "id": 60, "name": "Content creation" },
  { "id": 61, "name": "Blogging" },
  { "id": 62, "name": "Vlogging" },
  { "id": 63, "name": "Creative direction" },
  { "id": 64, "name": "Fashion design" },
  { "id": 65, "name": "Interior design" },
  { "id": 66, "name": "Product design" },
  { "id": 67, "name": "Furniture making" },
  { "id": 68, "name": "Carpentry" },
  { "id": 69, "name": "Gardening" },
  { "id": 70, "name": "Cooking" },
  { "id": 71, "name": "Baking" },
  { "id": 72, "name": "Bartending" },
  { "id": 73, "name": "Wine tasting" },
  { "id": 74, "name": "Mixology" },
  { "id": 75, "name": "Fitness training" },
  { "id": 76, "name": "Yoga instruction" },
  { "id": 77, "name": "Meditation" },
  { "id": 78, "name": "Life coaching" },
  { "id": 79, "name": "Financial planning" },
  { "id": 80, "name": "Investing" },
  { "id": 81, "name": "Accounting" },
  { "id": 82, "name": "Budgeting" },
  { "id": 83, "name": "Tax preparation" },
  { "id": 84, "name": "Grant writing" },
  { "id": 85, "name": "Real estate" },
  { "id": 86, "name": "Property management" },
  { "id": 87, "name": "Legal research" },
  { "id": 88, "name": "Compliance" },
  { "id": 89, "name": "Contract negotiation" },
  { "id": 90, "name": "Human resources" },
  { "id": 91, "name": "Recruiting" },
  { "id": 92, "name": "Interviewing" },
  { "id": 93, "name": "Employee training" },
  { "id": 94, "name": "Team building" },
  { "id": 95, "name": "Crisis management" },
  { "id": 96, "name": "Risk management" },
  { "id": 97, "name": "Customer relationship management (CRM)" },
  { "id": 98, "name": "Logistics" },
  { "id": 99, "name": "Supply chain management" },
  { "id": 100, "name": "Data visualization" },
  { "id": 101, "name": "Mathematics" },
  { "id": 102, "name": "Engineering" },
  { "id": 103, "name": "Construction management" },
  { "id": 104, "name": "Architecture" },
  { "id": 105, "name": "Geography" },
  { "id": 106, "name": "Urban planning" },
  { "id": 107, "name": "Ecology" },
  { "id": 108, "name": "Sustainability" },
  { "id": 109, "name": "Environmental science" },
  { "id": 110, "name": "Clothing design" },
  { "id": 111, "name": "Crafting" },
  { "id": 112, "name": "DIY projects" },
  { "id": 113, "name": "Sculpting" },
  { "id": 114, "name": "Painting" },
  { "id": 115, "name": "Drawing" },
  { "id": 116, "name": "Sketching" },
  { "id": 117, "name": "Printmaking" },
  { "id": 118, "name": "Pottery" },
  { "id": 119, "name": "Calligraphy" },
  { "id": 120, "name": "Woodworking" },
  { "id": 121, "name": "Metalworking" },
  { "id": 122, "name": "Jewelry making" },
  { "id": 123, "name": "Leatherworking" },
  { "id": 124, "name": "Photography editing" },
  { "id": 125, "name": "Pet care" },
  { "id": 126, "name": "Dog training" },
  { "id": 127, "name": "Animal behavior" },
  { "id": 128, "name": "Horseback riding" },
  { "id": 129, "name": "Swimming" },
  { "id": 130, "name": "Scuba diving" },
  { "id": 131, "name": "Mountain climbing" },
  { "id": 132, "name": "Rock climbing" },
  { "id": 133, "name": "Caving" },
  { "id": 134, "name": "Camping" },
  { "id": 135, "name": "Hiking" },
  { "id": 136, "name": "Cycling" },
  { "id": 137, "name": "Running" },
  { "id": 138, "name": "Skiing" },
  { "id": 139, "name": "Snowboarding" },
  { "id": 140, "name": "Surfing" },
  { "id": 141, "name": "Skateboarding" },
  { "id": 142, "name": "Flying drones" },
  { "id": 143, "name": "Astronomy" },
  { "id": 144, "name": "Space exploration" },
  { "id": 145, "name": "Antiquing" },
  { "id": 146, "name": "Collecting" },
  { "id": 147, "name": "Restoration" },
  { "id": 148, "name": "Beekeeping" },
  { "id": 149, "name": "Cheese making" },
  { "id": 150, "name": "Beer brewing" },
  { "id": 151, "name": "Coffee roasting" },
  { "id": 152, "name": "Candle making" },
  { "id": 153, "name": "Soap making" },
  { "id": 154, "name": "Self-defense" },
  { "id": 155, "name": "Martial arts" },
  { "id": 156, "name": "First aid" },
  { "id": 157, "name": "Emergency response" },
  { "id": 158, "name": "Mental health counseling" },
  { "id": 159, "name": "Therapy" },
  { "id": 160, "name": "Psychology" },
  { "id": 161, "name": "Social work" },
  { "id": 162, "name": "Coaching" },
  { "id": 163, "name": "Counseling" },
  { "id": 164, "name": "Social media strategy" },
  { "id": 165, "name": "Digital content creation" },
  { "id": 166, "name": "Podcasting" },
  { "id": 167, "name": "Voiceover work" },
  { "id": 168, "name": "Improv" },
  { "id": 169, "name": "Stand-up comedy" },
  { "id": 170, "name": "Scriptwriting" },
  { "id": 171, "name": "Game development" },
  { "id": 172, "name": "Virtual reality" },
  { "id": 173, "name": "Augmented reality" },
  { "id": 174, "name": "Board game design" },
  { "id": 175, "name": "Tabletop role-playing games" },
  { "id": 176, "name": "Magic tricks" },
  { "id": 177, "name": "Strategy games" },
  { "id": 178, "name": "Esports" },
  { "id": 179, "name": "Music composition" },
  { "id": 180, "name": "Instrumental music" },
  { "id": 181, "name": "Vocal performance" },
  { "id": 182, "name": "Singing" },
  { "id": 183, "name": "Songwriting" },
  { "id": 184, "name": "Music production" },
  { "id": 185, "name": "DJing" },
  { "id": 186, "name": "Sound engineering" },
  { "id": 187, "name": "Live performance" },
  { "id": 188, "name": "Concert promotion" },
  { "id": 189, "name": "Music theory" },
  { "id": 190, "name": "Music history" },
  { "id": 191, "name": "Music education" },
  { "id": 192, "name": "Choreography" },
  { "id": 193, "name": "Dance" },
  { "id": 194, "name": "Theater production" },
  { "id": 195, "name": "Acting" },
  { "id": 196, "name": "Stage management" },
  { "id": 197, "name": "Directing" },
  { "id": 198, "name": "Screenwriting" },
  { "id": 199, "name": "Film production" },
  { "id": 200, "name": "Cinematography" },
  { "id": 201, "name": "Film criticism" },
  { "id": 202, "name": "Film history" },
  { "id": 203, "name": "Film distribution" },
  { "id": 204, "name": "Script analysis" },
  { "id": 209, "name": "Backend development" },
  { "id": 210, "name": "Frontend development" },
  { "id": 211, "name": "Presentation Skills" },
  { "id": 212, "name": "Analytical Reasoning" },
  { "id": 213, "name": "Collaboration Techniques" },
  { "id": 214, "name": "Event Coordination" },
  { "id": 215, "name": "Client Support" },
  { "id": 216, "name": "Campaign Planning" },
  { "id": 217, "name": "3D Animation" },
  { "id": 218, "name": "Network Security" },
  { "id": 219, "name": "Encryption Techniques" },
  { "id": 220, "name": "Cloud Storage Solutions" },
  { "id": 221, "name": "Sound Mixing" },
  { "id": 222, "name": "Media Relations" },
  { "id": 223, "name": "Art Direction" },
  { "id": 224, "name": "Space Planning" },
  { "id": 225, "name": "Prototype Development" },
  { "id": 226, "name": "Cabinet Making" },
  { "id": 227, "name": "Landscape Design" },
  { "id": 228, "name": "Viticulture Basics" },
  { "id": 229, "name": "Mindfulness Techniques" },
  { "id": 230, "name": "Career Coaching" },
  { "id": 231, "name": "Retirement Planning" },
  { "id": 232, "name": "Portfolio Management" },
  { "id": 233, "name": "Tax Accounting" },
  { "id": 234, "name": "Expense Tracking" },
  { "id": 235, "name": "Tax Filing" },
  { "id": 236, "name": "Proposal Development" },
  { "id": 237, "name": "Property Appraisal" },
  { "id": 238, "name": "Tenant Relations" },
  { "id": 239, "name": "Case Law Analysis" },
  { "id": 240, "name": "Regulatory Compliance" },
  { "id": 241, "name": "Deal Structuring" },
  { "id": 242, "name": "Employee Benefits" },
  { "id": 243, "name": "Candidate Sourcing" },
  { "id": 244, "name": "Behavioral Interviewing" },
  { "id": 245, "name": "Onboarding Programs" },
  { "id": 246, "name": "Team Workshops" },
  { "id": 247, "name": "Disaster Recovery" },
  { "id": 248, "name": "Risk Assessment" },
  { "id": 249, "name": "Customer Retention Strategies" },
  { "id": 250, "name": "Supply Chain Optimization" },
  { "id": 251, "name": "Inventory Management" },
  { "id": 252, "name": "Statistics" },
  { "id": 253, "name": "Civil Engineering" },
  { "id": 254, "name": "Project Scheduling" },
  { "id": 255, "name": "Architectural Design" },
  { "id": 256, "name": "Geospatial Analysis" },
  { "id": 257, "name": "Zoning Regulations" },
  { "id": 258, "name": "Ecosystem Services" },
  { "id": 259, "name": "Renewable Energy Systems" },
  { "id": 260, "name": "Climate Change Studies" },
  { "id": 261, "name": "Clay Modeling" },
  { "id": 262, "name": "Oil Painting" },
  { "id": 263, "name": "Lithography" },
  { "id": 264, "name": "Wheel Throwing" },
  { "id": 265, "name": "Hand Lettering" },
  { "id": 266, "name": "Welding" },
  { "id": 267, "name": "Leather Stamping" },
  { "id": 268, "name": "Pet Grooming" },
  { "id": 269, "name": "Obedience Training" },
  { "id": 270, "name": "Animal Enrichment" },
  { "id": 271, "name": "Equestrian Care" },
  { "id": 272, "name": "Competitive Swimming" },
  { "id": 273, "name": "Deep Diving" },
  { "id": 274, "name": "Alpine Climbing" },
  { "id": 275, "name": "Bouldering" },
  { "id": 276, "name": "Spelunking" },
  { "id": 277, "name": "Wilderness Survival" },
  { "id": 278, "name": "Trail Navigation" },
  { "id": 279, "name": "Bike Maintenance" },
  { "id": 280, "name": "Marathon Training" },
  { "id": 281, "name": "Downhill Skiing" },
  { "id": 282, "name": "Freestyle Snowboarding" },
  { "id": 283, "name": "Wave Riding" },
  { "id": 284, "name": "Street Skateboarding" },
  { "id": 285, "name": "Artifact Restoration" },
  { "id": 286, "name": "Collectible Valuation" },
  { "id": 287, "name": "Furniture Restoration" },
  { "id": 288, "name": "Hive Management" },
  { "id": 289, "name": "Artisan Cheese Crafting" },
  { "id": 290, "name": "Home Brewing Techniques" },
  { "id": 291, "name": "Roast Profiling" },
  { "id": 292, "name": "Scented Candle Design" },
  { "id": 293, "name": "Natural Soap Formulation" },
  { "id": 294, "name": "Cognitive Behavioral Therapy" },
  { "id": 295, "name": "Family Therapy" },
  { "id": 296, "name": "Developmental Psychology" },
  { "id": 297, "name": "Community Outreach" },
  { "id": 298, "name": "Leadership Coaching" },
  { "id": 299, "name": "Grief Counseling" },
  { "id": 300, "name": "Influencer Marketing" },
  { "id": 301, "name": "Multimedia Production" },
  { "id": 302, "name": "Audio Editing for Podcasts" },
  { "id": 303, "name": "Character Voice Acting" },
  { "id": 304, "name": "Comedic Timing" },
  { "id": 305, "name": "Joke Writing" },
  { "id": 306, "name": "Screenplay Formatting" },
  { "id": 307, "name": "VR Environment Design" },
  { "id": 308, "name": "AR Application Development" },
  { "id": 309, "name": "Campaign Design" },
  { "id": 310, "name": "Close-up Magic" },
  { "id": 311, "name": "Chess Strategy" },
  { "id": 312, "name": "Competitive Gaming Tactics" },
  { "id": 313, "name": "Piano Performance" },
  { "id": 314, "name": "Vocal Warm-ups" },
  { "id": 315, "name": "Vocal Range Expansion" },
  { "id": 316, "name": "Lyric Writing" },
  { "id": 317, "name": "Stage Presence" },
  { "id": 318, "name": "Ticket Sales Strategies" },
  { "id": 319, "name": "Harmony and Counterpoint" },
  { "id": 320, "name": "Baroque Period Studies" },
  { "id": 321, "name": "Music Pedagogy" },
  { "id": 322, "name": "Set Design" },
  { "id": 323, "name": "Cue Sheet Management" },
  { "id": 324, "name": "Cinematic Direction" },
  { "id": 325, "name": "Dialogue Writing" },
  { "id": 326, "name": "Film Analysis" },
  { "id": 327, "name": "Silent Era Studies" },
  { "id": 328, "name": "Film Licensing" },
  { "id": 329, "name": "Character Arc Analysis" },
  { "id": 330, "name": "Home Maintenance" },
  { "id": 331, "name": "Plumbing Basics" },
  { "id": 332, "name": "Electrical Wiring" },
  { "id": 333, "name": "Appliance Repair" },
  { "id": 334, "name": "Sewing & Textiles" },
  { "id": 335, "name": "Knitting" },
  { "id": 336, "name": "Embroidery" },
  { "id": 337, "name": "Tailoring" },
  { "id": 338, "name": "Caregiving" },
  { "id": 339, "name": "Parenting Strategies" },
  { "id": 340, "name": "Diaper Changing" },
  { "id": 341, "name": "Palliative Care" },
  { "id": 342, "name": "Food Preservation" },
  { "id": 343, "name": "Canning" },
  { "id": 344, "name": "Fermentation" },
  { "id": 345, "name": "Dehydrating" },
  { "id": 346, "name": "Nutrition Science" },
  { "id": 347, "name": "Meal Planning" },
  { "id": 348, "name": "Dietary Restrictions" },
  { "id": 349, "name": "Mental Health First Aid" },
  { "id": 350, "name": "Suicide Prevention" },
  { "id": 351, "name": "Trauma Support" },
  { "id": 352, "name": "Alternative Medicine" },
  { "id": 353, "name": "Herbalism" },
  { "id": 354, "name": "Acupressure" },
  { "id": 355, "name": "Reiki" },
  { "id": 356, "name": "Activism" },
  { "id": 357, "name": "Protest Organizing" },
  { "id": 358, "name": "Grassroots Campaigning" },
  { "id": 359, "name": "Volunteer Management" },
  { "id": 360, "name": "NGO Coordination" },
  { "id": 361, "name": "Disaster Relief Logistics" },
  { "id": 362, "name": "Local Governance" },
  { "id": 363, "name": "Public Policy Analysis" },
  { "id": 364, "name": "Town Hall Moderation" },
  { "id": 365, "name": "Digital Art" },
  { "id": 366, "name": "Pixel Art" },
  { "id": 367, "name": "NFT Creation" },
  { "id": 368, "name": "3D Printing" },
  { "id": 369, "name": "Performance Art" },
  { "id": 370, "name": "Mime" },
  { "id": 371, "name": "Puppetry" },
  { "id": 372, "name": "Street Theater" },
  { "id": 373, "name": "Culinary Arts" },
  { "id": 374, "name": "Food Styling" },
  { "id": 375, "name": "Molecular Gastronomy" },
  { "id": 376, "name": "Quantum Computing" },
  { "id": 377, "name": "Qubit Manipulation" },
  { "id": 378, "name": "Quantum Algorithms" },
  { "id": 379, "name": "Blockchain" },
  { "id": 380, "name": "Smart Contracts" },
  { "id": 381, "name": "DAO Governance" },
  { "id": 382, "name": "Robotics" },
  { "id": 383, "name": "Drone Programming" },
  { "id": 384, "name": "Humanoid Robot Design" },
  { "id": 385, "name": "Aviation" },
  { "id": 386, "name": "Pilot Licensing" },
  { "id": 387, "name": "Aircraft Maintenance" },
  { "id": 388, "name": "Maritime Skills" },
  { "id": 389, "name": "Sailing" },
  { "id": 390, "name": "Boat Repair" },
  { "id": 391, "name": "Automotive" },
  { "id": 392, "name": "Car Repair" },
  { "id": 393, "name": "EV Battery Maintenance" },
  { "id": 394, "name": "Pedagogy" },
  { "id": 395, "name": "Lesson Planning" },
  { "id": 396, "name": "Classroom Management" },
  { "id": 397, "name": "E-Learning" },
  { "id": 398, "name": "LMS Administration" },
  { "id": 399, "name": "Gamified Course Design" },
  { "id": 400, "name": "Tutoring" },
  { "id": 401, "name": "Subject-Specific Coaching" },
  { "id": 402, "name": "SAT Prep" },
  { "id": 403, "name": "Nonverbal Communication" },
  { "id": 404, "name": "Body Language" },
  { "id": 405, "name": "ASL (American Sign Language)" },
  { "id": 406, "name": "Linguistics" },
  { "id": 407, "name": "Phonetics" },
  { "id": 408, "name": "Semiotics" },
  { "id": 409, "name": "Technical Writing" },
  { "id": 410, "name": "API Documentation" },
  { "id": 411, "name": "Scientific Papers" },
  { "id": 412, "name": "Religious Rituals" },
  { "id": 413, "name": "Ceremonial Practices" },
  { "id": 414, "name": "Wedding Ceremonies" },
  { "id": 415, "name": "Mindfulness Practices" },
  { "id": 416, "name": "Journaling" },
  { "id": 417, "name": "Gratitude Rituals" },
  { "id": 418, "name": "Astrology/Tarot" },
  { "id": 419, "name": "Chart Reading" },
  { "id": 420, "name": "Divination" },
  { "id": 421, "name": "Construction Trades" },
  { "id": 422, "name": "Masonry" },
  { "id": 424, "name": "Agriculture" },
  { "id": 425, "name": "Crop Rotation" },
  { "id": 426, "name": "Livestock Management" },
  { "id": 427, "name": "Manufacturing" },
  { "id": 428, "name": "CNC Machining" },
  { "id": 429, "name": "Textile Production" },
  { "id": 430, "name": "Citizen Science" },
  { "id": 431, "name": "Birdwatching" },
  { "id": 432, "name": "Water Quality Testing" },
  { "id": 433, "name": "Lab Techniques" },
  { "id": 434, "name": "Microscopy" },
  { "id": 435, "name": "PCR Testing" },
  { "id": 436, "name": "Fieldwork" },
  { "id": 437, "name": "Archaeological Excavation" },
  { "id": 438, "name": "Ethnography" },
  { "id": 439, "name": "Collectibles" },
  { "id": 440, "name": "Coin/Stamp Collecting" },
  { "id": 441, "name": "Antique Restoration" },
  { "id": 442, "name": "Model Building" },
  { "id": 443, "name": "LEGO Engineering" },
  { "id": 444, "name": "Miniature Painting" },
  { "id": 445, "name": "Cosplay" },
  { "id": 446, "name": "Costume Design" },
  { "id": 447, "name": "Prop Fabrication" },
  { "id": 448, "name": "Garden Tending" },
  { "id": 533, "name": "Reality Checks" },
  { "id": 534, "name": "Energy Work" },
  { "id": 535, "name": "Chakra Balancing" },
  { "id": 536, "name": "Sacred Geometry" },
  { "id": 537, "name": "Numerology" },
  { "id": 538, "name": "Palmistry" },
  { "id": 539, "name": "Rune Reading" },
  { "id": 540, "name": "Shamanic Journeying" },
  { "id": 541, "name": "Lucid Dreaming" },
  { "id": 542, "name": "Dream Journaling" }
]

Input:

Projects
[
  { "name": "${projectName}", "description": "${projectDescription}", "tags": ["${tags}"], "creator_id": "${creator_id}" }
]

Expected Output Format:

{
  "projects": [
    { "id": 1, "name": "${projectName}", "description": "${projectDescription}", "tags": ["tag1", "tag2"], "creator_id": ${creator_id} } 
  ],
  "tasks": [
    { "id": 1, "name": "Task Name", "description": "Task Desc", "project_id": 1, "skill_id": 1, "dependencies": [], "reward_tokens": 80 },
    { "id": 2, "name": "Task Name", "description": "Task Desc", "project_id": 1, "skill_id": 2, "dependencies": [1], "reward_tokens": 120 },
    { "id": 3, "name": "Task Name", "description": "Task Desc", "project_id": 1, "skill_id": 2, "dependencies": [1,2], "reward_tokens": 60 }
  ]
}


Notes:

ONLY return the JSON object described.
Dependencies are the IDs of the tasks that must be completed before this task can be started. THere can be multiple.
`;

  const result = await model.generateContent(prompt);
  const text = result.response.text();
  console.log('LLM response:', text);
  // Attempt to safely parse JSON from LLM output
  try {
    return parseLLMTasksResponse(text); // Use the more specific parser for tasks
  } catch (err) {
    console.error('Failed to parse LLM response for subtasks:', text);
    throw new Error('Failed to parse tasks from LLM output for subtasks');
  }
};


export const autoGenerateTasks = async (projectName, projectDescription, tags, creator_id) => {

  const prompt = `
You are an expert Project Manager AI. Your objective is to take the given project name and description and output the tasks and dependencies necessary to complete the project. You will generate output for the following database tables: projects and tasks.

Here are the rules:
- All IDs (project IDs, task IDs) must be **unique integers starting at 1**.
- Maintain **relationships**: 
  - "project_id" in tasks must match the corresponding project's new ID.
  - "skill_id" in tasks must match the correct skill's existing ID.
  - "dependencies" in tasks must reference the correct **new task IDs**.
- Output data in **JSON format**, with **one array per table** (projects, tasks).

Here is the **Skills List** with assigned IDs:
json
[
  { "id": 1, "name": "Project management" },
  { "id": 2, "name": "Time management" },
  { "id": 3, "name": "Leadership" },
  { "id": 4, "name": "Public speaking" },
  { "id": 5, "name": "Problem-solving" },
  { "id": 6, "name": "Critical thinking" },
  { "id": 7, "name": "Teamwork" },
  { "id": 8, "name": "Research" },
  { "id": 9, "name": "Data analysis" },
  { "id": 10, "name": "Programming" },
  { "id": 11, "name": "Writing" },
  { "id": 12, "name": "Creative writing" },
  { "id": 13, "name": "Technical writing" },
  { "id": 14, "name": "Design" },
  { "id": 15, "name": "Graphic design" },
  { "id": 16, "name": "Web development" },
  { "id": 17, "name": "UX/UI design" },
  { "id": 18, "name": "Digital marketing" },
  { "id": 19, "name": "SEO" },
  { "id": 20, "name": "Social media management" },
  { "id": 21, "name": "Email marketing" },
  { "id": 22, "name": "Event planning" },
  { "id": 23, "name": "Conflict resolution" },
  { "id": 24, "name": "Customer service" },
  { "id": 25, "name": "Sales" },
  { "id": 26, "name": "Negotiation" },
  { "id": 27, "name": "Marketing strategy" },
  { "id": 28, "name": "Branding" },
  { "id": 29, "name": "Photography" },
  { "id": 30, "name": "Videography" },
  { "id": 31, "name": "Film editing" },
  { "id": 32, "name": "Animation" },
  { "id": 33, "name": "3D modeling" },
  { "id": 34, "name": "App development" },
  { "id": 35, "name": "Mobile web development" },
  { "id": 36, "name": "Database management" },
  { "id": 37, "name": "Machine learning" },
  { "id": 38, "name": "Artificial intelligence" },
  { "id": 39, "name": "Networking" },
  { "id": 40, "name": "Cybersecurity" },
  { "id": 41, "name": "Cloud computing" },
  { "id": 42, "name": "Graphic design software" },
  { "id": 43, "name": "Microsoft Office Suite" },
  { "id": 44, "name": "Excel" },
  { "id": 45, "name": "PowerPoint" },
  { "id": 46, "name": "Photoshop" },
  { "id": 47, "name": "Illustrator" },
  { "id": 48, "name": "Final Cut Pro" },
  { "id": 49, "name": "AutoCAD" },
  { "id": 50, "name": "Sketch" },
  { "id": 51, "name": "Figma" },
  { "id": 52, "name": "InDesign" },
  { "id": 53, "name": "Video production" },
  { "id": 54, "name": "Audio production" },
  { "id": 55, "name": "Editing" },
  { "id": 56, "name": "Public relations" },
  { "id": 57, "name": "Foreign languages" },
  { "id": 58, "name": "Translation" },
  { "id": 59, "name": "Copywriting" },
  { "id": 60, "name": "Content creation" },
  { "id": 61, "name": "Blogging" },
  { "id": 62, "name": "Vlogging" },
  { "id": 63, "name": "Creative direction" },
  { "id": 64, "name": "Fashion design" },
  { "id": 65, "name": "Interior design" },
  { "id": 66, "name": "Product design" },
  { "id": 67, "name": "Furniture making" },
  { "id": 68, "name": "Carpentry" },
  { "id": 69, "name": "Gardening" },
  { "id": 70, "name": "Cooking" },
  { "id": 71, "name": "Baking" },
  { "id": 72, "name": "Bartending" },
  { "id": 73, "name": "Wine tasting" },
  { "id": 74, "name": "Mixology" },
  { "id": 75, "name": "Fitness training" },
  { "id": 76, "name": "Yoga instruction" },
  { "id": 77, "name": "Meditation" },
  { "id": 78, "name": "Life coaching" },
  { "id": 79, "name": "Financial planning" },
  { "id": 80, "name": "Investing" },
  { "id": 81, "name": "Accounting" },
  { "id": 82, "name": "Budgeting" },
  { "id": 83, "name": "Tax preparation" },
  { "id": 84, "name": "Grant writing" },
  { "id": 85, "name": "Real estate" },
  { "id": 86, "name": "Property management" },
  { "id": 87, "name": "Legal research" },
  { "id": 88, "name": "Compliance" },
  { "id": 89, "name": "Contract negotiation" },
  { "id": 90, "name": "Human resources" },
  { "id": 91, "name": "Recruiting" },
  { "id": 92, "name": "Interviewing" },
  { "id": 93, "name": "Employee training" },
  { "id": 94, "name": "Team building" },
  { "id": 95, "name": "Crisis management" },
  { "id": 96, "name": "Risk management" },
  { "id": 97, "name": "Customer relationship management (CRM)" },
  { "id": 98, "name": "Logistics" },
  { "id": 99, "name": "Supply chain management" },
  { "id": 100, "name": "Data visualization" },
  { "id": 101, "name": "Mathematics" },
  { "id": 102, "name": "Engineering" },
  { "id": 103, "name": "Construction management" },
  { "id": 104, "name": "Architecture" },
  { "id": 105, "name": "Geography" },
  { "id": 106, "name": "Urban planning" },
  { "id": 107, "name": "Ecology" },
  { "id": 108, "name": "Sustainability" },
  { "id": 109, "name": "Environmental science" },
  { "id": 110, "name": "Clothing design" },
  { "id": 111, "name": "Crafting" },
  { "id": 112, "name": "DIY projects" },
  { "id": 113, "name": "Sculpting" },
  { "id": 114, "name": "Painting" },
  { "id": 115, "name": "Drawing" },
  { "id": 116, "name": "Sketching" },
  { "id": 117, "name": "Printmaking" },
  { "id": 118, "name": "Pottery" },
  { "id": 119, "name": "Calligraphy" },
  { "id": 120, "name": "Woodworking" },
  { "id": 121, "name": "Metalworking" },
  { "id": 122, "name": "Jewelry making" },
  { "id": 123, "name": "Leatherworking" },
  { "id": 124, "name": "Photography editing" },
  { "id": 125, "name": "Pet care" },
  { "id": 126, "name": "Dog training" },
  { "id": 127, "name": "Animal behavior" },
  { "id": 128, "name": "Horseback riding" },
  { "id": 129, "name": "Swimming" },
  { "id": 130, "name": "Scuba diving" },
  { "id": 131, "name": "Mountain climbing" },
  { "id": 132, "name": "Rock climbing" },
  { "id": 133, "name": "Caving" },
  { "id": 134, "name": "Camping" },
  { "id": 135, "name": "Hiking" },
  { "id": 136, "name": "Cycling" },
  { "id": 137, "name": "Running" },
  { "id": 138, "name": "Skiing" },
  { "id": 139, "name": "Snowboarding" },
  { "id": 140, "name": "Surfing" },
  { "id": 141, "name": "Skateboarding" },
  { "id": 142, "name": "Flying drones" },
  { "id": 143, "name": "Astronomy" },
  { "id": 144, "name": "Space exploration" },
  { "id": 145, "name": "Antiquing" },
  { "id": 146, "name": "Collecting" },
  { "id": 147, "name": "Restoration" },
  { "id": 148, "name": "Beekeeping" },
  { "id": 149, "name": "Cheese making" },
  { "id": 150, "name": "Beer brewing" },
  { "id": 151, "name": "Coffee roasting" },
  { "id": 152, "name": "Candle making" },
  { "id": 153, "name": "Soap making" },
  { "id": 154, "name": "Self-defense" },
  { "id": 155, "name": "Martial arts" },
  { "id": 156, "name": "First aid" },
  { "id": 157, "name": "Emergency response" },
  { "id": 158, "name": "Mental health counseling" },
  { "id": 159, "name": "Therapy" },
  { "id": 160, "name": "Psychology" },
  { "id": 161, "name": "Social work" },
  { "id": 162, "name": "Coaching" },
  { "id": 163, "name": "Counseling" },
  { "id": 164, "name": "Social media strategy" },
  { "id": 165, "name": "Digital content creation" },
  { "id": 166, "name": "Podcasting" },
  { "id": 167, "name": "Voiceover work" },
  { "id": 168, "name": "Improv" },
  { "id": 169, "name": "Stand-up comedy" },
  { "id": 170, "name": "Scriptwriting" },
  { "id": 171, "name": "Game development" },
  { "id": 172, "name": "Virtual reality" },
  { "id": 173, "name": "Augmented reality" },
  { "id": 174, "name": "Board game design" },
  { "id": 175, "name": "Tabletop role-playing games" },
  { "id": 176, "name": "Magic tricks" },
  { "id": 177, "name": "Strategy games" },
  { "id": 178, "name": "Esports" },
  { "id": 179, "name": "Music composition" },
  { "id": 180, "name": "Instrumental music" },
  { "id": 181, "name": "Vocal performance" },
  { "id": 182, "name": "Singing" },
  { "id": 183, "name": "Songwriting" },
  { "id": 184, "name": "Music production" },
  { "id": 185, "name": "DJing" },
  { "id": 186, "name": "Sound engineering" },
  { "id": 187, "name": "Live performance" },
  { "id": 188, "name": "Concert promotion" },
  { "id": 189, "name": "Music theory" },
  { "id": 190, "name": "Music history" },
  { "id": 191, "name": "Music education" },
  { "id": 192, "name": "Choreography" },
  { "id": 193, "name": "Dance" },
  { "id": 194, "name": "Theater production" },
  { "id": 195, "name": "Acting" },
  { "id": 196, "name": "Stage management" },
  { "id": 197, "name": "Directing" },
  { "id": 198, "name": "Screenwriting" },
  { "id": 199, "name": "Film production" },
  { "id": 200, "name": "Cinematography" },
  { "id": 201, "name": "Film criticism" },
  { "id": 202, "name": "Film history" },
  { "id": 203, "name": "Film distribution" },
  { "id": 204, "name": "Script analysis" },
  { "id": 209, "name": "Backend development" },
  { "id": 210, "name": "Frontend development" },
  { "id": 211, "name": "Presentation Skills" },
  { "id": 212, "name": "Analytical Reasoning" },
  { "id": 213, "name": "Collaboration Techniques" },
  { "id": 214, "name": "Event Coordination" },
  { "id": 215, "name": "Client Support" },
  { "id": 216, "name": "Campaign Planning" },
  { "id": 217, "name": "3D Animation" },
  { "id": 218, "name": "Network Security" },
  { "id": 219, "name": "Encryption Techniques" },
  { "id": 220, "name": "Cloud Storage Solutions" },
  { "id": 221, "name": "Sound Mixing" },
  { "id": 222, "name": "Media Relations" },
  { "id": 223, "name": "Art Direction" },
  { "id": 224, "name": "Space Planning" },
  { "id": 225, "name": "Prototype Development" },
  { "id": 226, "name": "Cabinet Making" },
  { "id": 227, "name": "Landscape Design" },
  { "id": 228, "name": "Viticulture Basics" },
  { "id": 229, "name": "Mindfulness Techniques" },
  { "id": 230, "name": "Career Coaching" },
  { "id": 231, "name": "Retirement Planning" },
  { "id": 232, "name": "Portfolio Management" },
  { "id": 233, "name": "Tax Accounting" },
  { "id": 234, "name": "Expense Tracking" },
  { "id": 235, "name": "Tax Filing" },
  { "id": 236, "name": "Proposal Development" },
  { "id": 237, "name": "Property Appraisal" },
  { "id": 238, "name": "Tenant Relations" },
  { "id": 239, "name": "Case Law Analysis" },
  { "id": 240, "name": "Regulatory Compliance" },
  { "id": 241, "name": "Deal Structuring" },
  { "id": 242, "name": "Employee Benefits" },
  { "id": 243, "name": "Candidate Sourcing" },
  { "id": 244, "name": "Behavioral Interviewing" },
  { "id": 245, "name": "Onboarding Programs" },
  { "id": 246, "name": "Team Workshops" },
  { "id": 247, "name": "Disaster Recovery" },
  { "id": 248, "name": "Risk Assessment" },
  { "id": 249, "name": "Customer Retention Strategies" },
  { "id": 250, "name": "Supply Chain Optimization" },
  { "id": 251, "name": "Inventory Management" },
  { "id": 252, "name": "Statistics" },
  { "id": 253, "name": "Civil Engineering" },
  { "id": 254, "name": "Project Scheduling" },
  { "id": 255, "name": "Architectural Design" },
  { "id": 256, "name": "Geospatial Analysis" },
  { "id": 257, "name": "Zoning Regulations" },
  { "id": 258, "name": "Ecosystem Services" },
  { "id": 259, "name": "Renewable Energy Systems" },
  { "id": 260, "name": "Climate Change Studies" },
  { "id": 261, "name": "Clay Modeling" },
  { "id": 262, "name": "Oil Painting" },
  { "id": 263, "name": "Lithography" },
  { "id": 264, "name": "Wheel Throwing" },
  { "id": 265, "name": "Hand Lettering" },
  { "id": 266, "name": "Welding" },
  { "id": 267, "name": "Leather Stamping" },
  { "id": 268, "name": "Pet Grooming" },
  { "id": 269, "name": "Obedience Training" },
  { "id": 270, "name": "Animal Enrichment" },
  { "id": 271, "name": "Equestrian Care" },
  { "id": 272, "name": "Competitive Swimming" },
  { "id": 273, "name": "Deep Diving" },
  { "id": 274, "name": "Alpine Climbing" },
  { "id": 275, "name": "Bouldering" },
  { "id": 276, "name": "Spelunking" },
  { "id": 277, "name": "Wilderness Survival" },
  { "id": 278, "name": "Trail Navigation" },
  { "id": 279, "name": "Bike Maintenance" },
  { "id": 280, "name": "Marathon Training" },
  { "id": 281, "name": "Downhill Skiing" },
  { "id": 282, "name": "Freestyle Snowboarding" },
  { "id": 283, "name": "Wave Riding" },
  { "id": 284, "name": "Street Skateboarding" },
  { "id": 285, "name": "Artifact Restoration" },
  { "id": 286, "name": "Collectible Valuation" },
  { "id": 287, "name": "Furniture Restoration" },
  { "id": 288, "name": "Hive Management" },
  { "id": 289, "name": "Artisan Cheese Crafting" },
  { "id": 290, "name": "Home Brewing Techniques" },
  { "id": 291, "name": "Roast Profiling" },
  { "id": 292, "name": "Scented Candle Design" },
  { "id": 293, "name": "Natural Soap Formulation" },
  { "id": 294, "name": "Cognitive Behavioral Therapy" },
  { "id": 295, "name": "Family Therapy" },
  { "id": 296, "name": "Developmental Psychology" },
  { "id": 297, "name": "Community Outreach" },
  { "id": 298, "name": "Leadership Coaching" },
  { "id": 299, "name": "Grief Counseling" },
  { "id": 300, "name": "Influencer Marketing" },
  { "id": 301, "name": "Multimedia Production" },
  { "id": 302, "name": "Audio Editing for Podcasts" },
  { "id": 303, "name": "Character Voice Acting" },
  { "id": 304, "name": "Comedic Timing" },
  { "id": 305, "name": "Joke Writing" },
  { "id": 306, "name": "Screenplay Formatting" },
  { "id": 307, "name": "VR Environment Design" },
  { "id": 308, "name": "AR Application Development" },
  { "id": 309, "name": "Campaign Design" },
  { "id": 310, "name": "Close-up Magic" },
  { "id": 311, "name": "Chess Strategy" },
  { "id": 312, "name": "Competitive Gaming Tactics" },
  { "id": 313, "name": "Piano Performance" },
  { "id": 314, "name": "Vocal Warm-ups" },
  { "id": 315, "name": "Vocal Range Expansion" },
  { "id": 316, "name": "Lyric Writing" },
  { "id": 317, "name": "Stage Presence" },
  { "id": 318, "name": "Ticket Sales Strategies" },
  { "id": 319, "name": "Harmony and Counterpoint" },
  { "id": 320, "name": "Baroque Period Studies" },
  { "id": 321, "name": "Music Pedagogy" },
  { "id": 322, "name": "Set Design" },
  { "id": 323, "name": "Cue Sheet Management" },
  { "id": 324, "name": "Cinematic Direction" },
  { "id": 325, "name": "Dialogue Writing" },
  { "id": 326, "name": "Film Analysis" },
  { "id": 327, "name": "Silent Era Studies" },
  { "id": 328, "name": "Film Licensing" },
  { "id": 329, "name": "Character Arc Analysis" },
  { "id": 330, "name": "Home Maintenance" },
  { "id": 331, "name": "Plumbing Basics" },
  { "id": 332, "name": "Electrical Wiring" },
  { "id": 333, "name": "Appliance Repair" },
  { "id": 334, "name": "Sewing & Textiles" },
  { "id": 335, "name": "Knitting" },
  { "id": 336, "name": "Embroidery" },
  { "id": 337, "name": "Tailoring" },
  { "id": 338, "name": "Caregiving" },
  { "id": 339, "name": "Parenting Strategies" },
  { "id": 340, "name": "Diaper Changing" },
  { "id": 341, "name": "Palliative Care" },
  { "id": 342, "name": "Food Preservation" },
  { "id": 343, "name": "Canning" },
  { "id": 344, "name": "Fermentation" },
  { "id": 345, "name": "Dehydrating" },
  { "id": 346, "name": "Nutrition Science" },
  { "id": 347, "name": "Meal Planning" },
  { "id": 348, "name": "Dietary Restrictions" },
  { "id": 349, "name": "Mental Health First Aid" },
  { "id": 350, "name": "Suicide Prevention" },
  { "id": 351, "name": "Trauma Support" },
  { "id": 352, "name": "Alternative Medicine" },
  { "id": 353, "name": "Herbalism" },
  { "id": 354, "name": "Acupressure" },
  { "id": 355, "name": "Reiki" },
  { "id": 356, "name": "Activism" },
  { "id": 357, "name": "Protest Organizing" },
  { "id": 358, "name": "Grassroots Campaigning" },
  { "id": 359, "name": "Volunteer Management" },
  { "id": 360, "name": "NGO Coordination" },
  { "id": 361, "name": "Disaster Relief Logistics" },
  { "id": 362, "name": "Local Governance" },
  { "id": 363, "name": "Public Policy Analysis" },
  { "id": 364, "name": "Town Hall Moderation" },
  { "id": 365, "name": "Digital Art" },
  { "id": 366, "name": "Pixel Art" },
  { "id": 367, "name": "NFT Creation" },
  { "id": 368, "name": "3D Printing" },
  { "id": 369, "name": "Performance Art" },
  { "id": 370, "name": "Mime" },
  { "id": 371, "name": "Puppetry" },
  { "id": 372, "name": "Street Theater" },
  { "id": 373, "name": "Culinary Arts" },
  { "id": 374, "name": "Food Styling" },
  { "id": 375, "name": "Molecular Gastronomy" },
  { "id": 376, "name": "Quantum Computing" },
  { "id": 377, "name": "Qubit Manipulation" },
  { "id": 378, "name": "Quantum Algorithms" },
  { "id": 379, "name": "Blockchain" },
  { "id": 380, "name": "Smart Contracts" },
  { "id": 381, "name": "DAO Governance" },
  { "id": 382, "name": "Robotics" },
  { "id": 383, "name": "Drone Programming" },
  { "id": 384, "name": "Humanoid Robot Design" },
  { "id": 385, "name": "Aviation" },
  { "id": 386, "name": "Pilot Licensing" },
  { "id": 387, "name": "Aircraft Maintenance" },
  { "id": 388, "name": "Maritime Skills" },
  { "id": 389, "name": "Sailing" },
  { "id": 390, "name": "Boat Repair" },
  { "id": 391, "name": "Automotive" },
  { "id": 392, "name": "Car Repair" },
  { "id": 393, "name": "EV Battery Maintenance" },
  { "id": 394, "name": "Pedagogy" },
  { "id": 395, "name": "Lesson Planning" },
  { "id": 396, "name": "Classroom Management" },
  { "id": 397, "name": "E-Learning" },
  { "id": 398, "name": "LMS Administration" },
  { "id": 399, "name": "Gamified Course Design" },
  { "id": 400, "name": "Tutoring" },
  { "id": 401, "name": "Subject-Specific Coaching" },
  { "id": 402, "name": "SAT Prep" },
  { "id": 403, "name": "Nonverbal Communication" },
  { "id": 404, "name": "Body Language" },
  { "id": 405, "name": "ASL (American Sign Language)" },
  { "id": 406, "name": "Linguistics" },
  { "id": 407, "name": "Phonetics" },
  { "id": 408, "name": "Semiotics" },
  { "id": 409, "name": "Technical Writing" },
  { "id": 410, "name": "API Documentation" },
  { "id": 411, "name": "Scientific Papers" },
  { "id": 412, "name": "Religious Rituals" },
  { "id": 413, "name": "Ceremonial Practices" },
  { "id": 414, "name": "Wedding Ceremonies" },
  { "id": 415, "name": "Mindfulness Practices" },
  { "id": 416, "name": "Journaling" },
  { "id": 417, "name": "Gratitude Rituals" },
  { "id": 418, "name": "Astrology/Tarot" },
  { "id": 419, "name": "Chart Reading" },
  { "id": 420, "name": "Divination" },
  { "id": 421, "name": "Construction Trades" },
  { "id": 422, "name": "Masonry" },
  { "id": 424, "name": "Agriculture" },
  { "id": 425, "name": "Crop Rotation" },
  { "id": 426, "name": "Livestock Management" },
  { "id": 427, "name": "Manufacturing" },
  { "id": 428, "name": "CNC Machining" },
  { "id": 429, "name": "Textile Production" },
  { "id": 430, "name": "Citizen Science" },
  { "id": 431, "name": "Birdwatching" },
  { "id": 432, "name": "Water Quality Testing" },
  { "id": 433, "name": "Lab Techniques" },
  { "id": 434, "name": "Microscopy" },
  { "id": 435, "name": "PCR Testing" },
  { "id": 436, "name": "Fieldwork" },
  { "id": 437, "name": "Archaeological Excavation" },
  { "id": 438, "name": "Ethnography" },
  { "id": 439, "name": "Collectibles" },
  { "id": 440, "name": "Coin/Stamp Collecting" },
  { "id": 441, "name": "Antique Restoration" },
  { "id": 442, "name": "Model Building" },
  { "id": 443, "name": "LEGO Engineering" },
  { "id": 444, "name": "Miniature Painting" },
  { "id": 445, "name": "Cosplay" },
  { "id": 446, "name": "Costume Design" },
  { "id": 447, "name": "Prop Fabrication" },
  { "id": 448, "name": "Garden Tending" },
  { "id": 533, "name": "Reality Checks" },
  { "id": 534, "name": "Energy Work" },
  { "id": 535, "name": "Chakra Balancing" },
  { "id": 536, "name": "Sacred Geometry" },
  { "id": 537, "name": "Numerology" },
  { "id": 538, "name": "Palmistry" },
  { "id": 539, "name": "Rune Reading" },
  { "id": 540, "name": "Shamanic Journeying" },
  { "id": 541, "name": "Lucid Dreaming" },
  { "id": 542, "name": "Dream Journaling" }
]

Input:

Projects
[
  { "name": "${projectName}", "description": "${projectDescription}", "tags": ["${tags}"], "creator_id": "${creator_id}" }
]

Expected Output Format:

{
  "projects": [
    { "id": 1, "name": "${projectName}", "description": "${projectDescription}", "tags": ["tag1", "tag2"], "creator_id": ${creator_id} } 
  ],
  "tasks": [
    { "id": 1, "name": "Task Name", "description": "Task Desc", "project_id": 1, "skill_id": 1, "dependencies": [], "reward_tokens": 80 },
    { "id": 2, "name": "Task Name", "description": "Task Desc", "project_id": 1, "skill_id": 2, "dependencies": [1], "reward_tokens": 120 },
    { "id": 3, "name": "Task Name", "description": "Task Desc", "project_id": 1, "skill_id": 2, "dependencies": [1,2], "reward_tokens": 60 }
  ]
}


Notes:

ONLY return the JSON object described.
Dependencies are the IDs of the tasks that must be completed before this task can be started. THere can be multiple.
`;

const result = await model.generateContent(prompt);
const text = result.response.text();
console.log('LLM response (generateSubtasks):', text);

try {
  // Assuming autoGenerateTasks also expects a "tasks" array in a root object
  const parsedData = parseLLMJsonResponse(text); 
  if (!parsedData.tasks || !Array.isArray(parsedData.tasks)) {
     // If the root object itself is the tasks array, this needs adjustment
     // For now, sticking to the pattern observed in parseLLMTasksResponse
    throw new Error('Tasks array missing or invalid in LLM response for autoGenerateTasks');
  }
  // The prompt for autoGenerateTasks expects a specific structure with "projects" and "tasks" keys.
  // The parseLLMJsonResponse will return the whole object.
  // The original parseLLMResponse was returning data.tasks.
  // Let's assume for now the calling code of autoGenerateTasks expects the full {projects: [], tasks: []} object.
  // If it only needs tasks, then it should be: return parsedData.tasks;
  return parsedData; // Return the full parsed object as per the prompt's expected output format
} catch (err) {
  console.error('Failed to parse LLM response for autoGenerateTasks:', text);
  throw new Error('Failed to parse subtasks from LLM output for autoGenerateTasks');
}
};