// src/audio/scenes/community.js
//
// "COMMUNITY HUB" — G Major, 84 BPM
//
// Busy conversational motifs. Diverse cell-based melodies.

export const communityScene = {
  bpm: 84,
  transitionTime: 2,
  mood: {
    stringsVol: -26,
    brassVol: -30,
    bassVol: -24,
    percVol: -30,
    reverbWet: 0.35,
    percussionActive: true,
    choirActive: true,
    arpActive: true,
    cyberActive: true,
    melodyActive: true,
    arpDensity: 0.5,
    cyberDensity: 0.5,
    bassIntensity: 0.7,
    melodicMaterial: {
      progressions: [
        [
          { notes: ['G2', 'D3', 'B3'] },
          { notes: ['C3', 'G3', 'E4'] },
          { notes: ['D3', 'A3', 'F#4'] },
          null,
          { notes: ['E3', 'G3', 'D4'] },
          { notes: ['C3', 'E3', 'A4'] },
          null,
          { notes: ['D3', 'G3', 'C4'] },
          { notes: ['G2', 'B2', 'D3', 'F#3'] },
          { notes: ['C3', 'E3', 'G3', 'D4'] },
          null,
          { notes: ['A2', 'C#3', 'E3', 'G3'] },
          { notes: ['D3', 'F#3', 'A3', 'C4'] },
          null,
          { notes: ['G3', 'B3', 'D4', 'F#4'] },
          { notes: ['C3', 'D3', 'G3', 'B3'] },
        ]
      ],
      slideCells: [
      [
        { note: 'G4', dur: '4n', vel: 0.1 },
        { note: 'Bb4', dur: '8n', vel: 0.12 },
        { note: 'C5', dur: '4n', vel: 0.11 },
        { note: 'Db5', dur: '8n', vel: 0.15 },
        { note: 'C5', dur: '2n', vel: 0.1 },
        null,
        null,
        null,
        { note: 'F4', dur: '4n', vel: 0.08 },
        { note: 'G4', dur: '1n', vel: 0.07 },
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'D5', dur: '2n', vel: 0.14 },
        null,
        { note: 'C5', dur: '8n', vel: 0.12 },
        { note: 'Bb4', dur: '8n', vel: 0.11 },
        { note: 'A4', dur: '4n', vel: 0.1 },
        { note: 'F4', dur: '4n', vel: 0.09 },
        { note: 'G4', dur: '1n', vel: 0.13 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        { note: 'G4', dur: '8n', vel: 0.11 },
        { note: 'G4', dur: '16n', vel: 0.12 },
        { note: 'Bb4', dur: '16n', vel: 0.13 },
        { note: 'C5', dur: '8n', vel: 0.14 },
        null,
        { note: 'Db5', dur: '8n', vel: 0.16 },
        { note: 'C5', dur: '8n', vel: 0.12 },
        { note: 'Bb4', dur: '4n', vel: 0.1 },
        { note: 'G4', dur: '2n', vel: 0.09 },
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'F5', dur: '2n', vel: 0.15 },
        { note: 'D5', dur: '4n', vel: 0.12 },
        { note: 'C5', dur: '4n', vel: 0.1 },
        { note: 'Bb4', dur: '1n', vel: 0.08 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        { note: 'G4', dur: '16n', vel: 0.12 },
        { note: 'Bb4', dur: '4n', vel: 0.14 },
        { note: 'G4', dur: '4n', vel: 0.1 },
        { note: 'F4', dur: '8n', vel: 0.09 },
        { note: 'D4', dur: '2n', vel: 0.08 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'G4', dur: '1n', vel: 0.15 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'Bb4', dur: '1n', vel: 0.12 },
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        { note: 'D5', dur: '2n', vel: 0.14 },
        null,
        { note: 'C5', dur: '8n', vel: 0.12 },
        { note: 'Bb4', dur: '8n', vel: 0.11 },
        { note: 'A4', dur: '4n', vel: 0.1 },
        { note: 'F4', dur: '4n', vel: 0.09 },
        { note: 'G4', dur: '1n', vel: 0.13 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'G4', dur: '16n', vel: 0.12 },
        { note: 'Bb4', dur: '4n', vel: 0.14 },
        { note: 'G4', dur: '4n', vel: 0.1 },
        { note: 'F4', dur: '8n', vel: 0.09 },
        { note: 'D4', dur: '2n', vel: 0.08 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
      ],
    starCells: [
        ['G5', 'B5', 'D6'],
        ['C6', 'E6', 'G6'],
      ],
      cyberCells: [
        ['G4', 'B4', 'D5', 'G5'],
        ['C5', 'E5', 'G5', 'E5'],
      ],
      bassNotes:  ['G1', 'D1', 'C1', 'E1', 'D1', 'A1', 'B1', 'G1'],
    }
  }
};