// src/audio/scenes/crisis.js
//
// "STAMPEDE / HULL BREACH" — E minor, 104 BPM
//
// Frantic tension phrases. Repetitive rhythmic anchors.

export const crisisScene = {
  bpm: 104,
  transitionTime: 0.3,
  mood: {
    stringsVol: -20,
    brassVol: -68,
    bassVol: -20,
    percVol: -26,
    reverbWet: 0.2,
    percussionActive: true,
    choirActive: false,
    arpActive: true,
    cyberActive: true,
    melodyActive: false,
    arpDensity: 0.8,
    cyberDensity: 0.7,
    bassIntensity: 0.9,
    melodicMaterial: {
      progressions: [
        [
          { notes: ['E2', 'B2', 'G3'] },    // Em
          { notes: ['C2', 'G2', 'D3'] },    // Cmaj9
          { notes: ['F#2', 'C#3', 'E3'] },  // F#dim/E
          { notes: ['B2', 'F#3', 'A3'] },   // B7
          { notes: ['E2', 'B2', 'D3'] },    // Em7
          { notes: ['A2', 'E3', 'G3'] },    // Am7
          { notes: ['D2', 'A2', 'C3'] },    // D7
          { notes: ['G2', 'D3', 'F#3'] },   // Gmaj7
          { notes: ['C2', 'G2', 'B2'] },    // Cmaj7
          { notes: ['F#2', 'A2', 'C3'] },   // F#m7b5
          { notes: ['B2', 'D#3', 'A3'] },   // B7b9
          { notes: ['E2', 'G2', 'B2'] },
          { notes: ['E2', 'B2', 'F#3'] },
          null,
          { notes: ['C2', 'E3', 'Bb3'] },   // C7
          { notes: ['B2', 'D#3', 'A3'] },
        ]
      ],
      slideCells: [
      [
        { note: 'G4', dur: '8n', vel: 0.11 },
        { note: 'G4', dur: '16n', vel: 0.12 },
        { note: 'Bb4', dur: '16n', vel: 0.13 },
        { note: 'C5', dur: '4n', vel: 0.1 },
        { note: 'Db5', dur: '8n', vel: 0.16 },
        { note: 'C5', dur: '2n', vel: 0.12 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'F5', dur: '2n', vel: 0.15 },
        { note: 'D5', dur: '4n', vel: 0.12 },
        { note: 'C5', dur: '1n', vel: 0.1 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        { note: 'G4', dur: '16n', vel: 0.12 },
        { note: 'Bb4', dur: '4n', vel: 0.14 },
        { note: 'G4', dur: '2n', vel: 0.1 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'G4', dur: '1n', vel: 0.15 },
        null,
        { note: 'Bb4', dur: '1n', vel: 0.12 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
      ],
    harmonicaCells: [
      [
        { note: 'G4', dur: '1n', vel: 0.15 },
        null,
        { note: 'Bb4', dur: '1n', vel: 0.12 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'G4', dur: '8n', vel: 0.11 },
        { note: 'G4', dur: '16n', vel: 0.12 },
        { note: 'Bb4', dur: '16n', vel: 0.13 },
        { note: 'C5', dur: '4n', vel: 0.1 },
        { note: 'Db5', dur: '8n', vel: 0.16 },
        { note: 'C5', dur: '2n', vel: 0.12 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        { note: 'F5', dur: '2n', vel: 0.15 },
        { note: 'D5', dur: '4n', vel: 0.12 },
        { note: 'C5', dur: '1n', vel: 0.1 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'G4', dur: '16n', vel: 0.12 },
        { note: 'Bb4', dur: '4n', vel: 0.14 },
        { note: 'G4', dur: '2n', vel: 0.1 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
      ],
      [
        { note: 'D5', dur: '2n', vel: 0.14 },
        null,
        { note: 'C5', dur: '8n', vel: 0.12 },
        { note: 'Bb4', dur: '8n', vel: 0.11 },
        { note: 'A4', dur: '4n', vel: 0.1 },
        { note: 'F4', dur: '4n', vel: 0.09 },
        { note: 'G4', dur: '1n', vel: 0.13 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'G4', dur: '1n', vel: 0.15 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'Bb4', dur: '1n', vel: 0.12 },
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
      ],
      [
        { note: 'G4', dur: '8n', vel: 0.11 },
        { note: 'G4', dur: '16n', vel: 0.12 },
        { note: 'Bb4', dur: '16n', vel: 0.13 },
        { note: 'C5', dur: '8n', vel: 0.14 },
        null,
        { note: 'Db5', dur: '8n', vel: 0.16 },
        { note: 'C5', dur: '8n', vel: 0.12 },
        { note: 'Bb4', dur: '4n', vel: 0.1 },
        { note: 'G4', dur: '2n', vel: 0.09 },
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'F5', dur: '2n', vel: 0.15 },
        { note: 'D5', dur: '4n', vel: 0.12 },
        { note: 'C5', dur: '4n', vel: 0.1 },
        { note: 'Bb4', dur: '1n', vel: 0.08 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        { note: 'G4', dur: '16n', vel: 0.12 },
        { note: 'Bb4', dur: '4n', vel: 0.14 },
        { note: 'G4', dur: '4n', vel: 0.1 },
        { note: 'F4', dur: '8n', vel: 0.09 },
        { note: 'D4', dur: '2n', vel: 0.08 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'G4', dur: '1n', vel: 0.15 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'Bb4', dur: '1n', vel: 0.12 },
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        { note: 'D5', dur: '2n', vel: 0.14 },
        null,
        { note: 'C5', dur: '8n', vel: 0.12 },
        { note: 'Bb4', dur: '8n', vel: 0.11 },
        { note: 'A4', dur: '4n', vel: 0.1 },
        { note: 'F4', dur: '4n', vel: 0.09 },
        { note: 'G4', dur: '1n', vel: 0.13 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'G4', dur: '16n', vel: 0.12 },
        { note: 'Bb4', dur: '4n', vel: 0.14 },
        { note: 'G4', dur: '4n', vel: 0.1 },
        { note: 'F4', dur: '8n', vel: 0.09 },
        { note: 'D4', dur: '2n', vel: 0.08 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
      ],

        ['F#5', 'A5', 'C6'],
      ],

        ['B3', 'D#4', 'F#4', 'A4'],
      ],
      bassNotes:  ['E1', 'E1', 'C1', 'C1', 'B1', 'B1', 'A1', 'F#1'],
    },
  },
};