// src/audio/scenes/guildHub.js
//
// "GUILD HUB" — G Major, 78 BPM
//
// Warm communal motifs. Conversational call and response.

export const guildHubScene = {
  bpm: 78,
  transitionTime: 3,
  mood: {
    stringsVol: -26,
    brassVol: -32,
    bassVol: -24,
    percVol: -36,
    reverbWet: 0.45,
    percussionActive: true,
    choirActive: true,
    arpActive: true,
    cyberActive: true,
    melodyActive: true,
    arpDensity: 0.3,
    cyberDensity: 0.3,
    bassIntensity: 0.5,
    melodicMaterial: {
      progressions: [
        [
          { notes: ['G2', 'D3', 'B3'] },     // G
          { notes: ['C3', 'G3', 'E4'] },     // C
          { notes: ['D3', 'A3', 'F#4'] },    // D
          null,
          { notes: ['E3', 'G3', 'B3'] },     // Em
          { notes: ['A2', 'C3', 'E3'] },     // Am
          null,
          { notes: ['D3', 'F#3', 'C4'] },    // D7
          { notes: ['G2', 'B2', 'D3', 'F#3'] }, // Gmaj7
          { notes: ['C3', 'E3', 'G3', 'B3'] },  // Cmaj7
          null,
          { notes: ['A2', 'E3', 'G3', 'C#4'] }, // A7
          { notes: ['D2', 'A2', 'D3', 'F#3'] }, // D
          null,
          { notes: ['G3', 'B3', 'E4'] },     // G/E
          { notes: ['C3', 'D3', 'G3'] },     // G/C
        ]
      ],
      slideCells: [
      [
        { note: 'G4', dur: '4n', vel: 0.1 },
        { note: 'Bb4', dur: '8n', vel: 0.12 },
        { note: 'C5', dur: '2n', vel: 0.15 },
        null,
        { note: 'F4', dur: '4n', vel: 0.08 },
        { note: 'G4', dur: '1n', vel: 0.1 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'D5', dur: '2n', vel: 0.14 },
        null,
        { note: 'C5', dur: '8n', vel: 0.12 },
        { note: 'Bb4', dur: '4n', vel: 0.1 },
        { note: 'G4', dur: '1n', vel: 0.08 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        { note: 'G4', dur: '8n', vel: 0.11 },
        { note: 'G4', dur: '16n', vel: 0.12 },
        { note: 'Bb4', dur: '16n', vel: 0.13 },
        { note: 'C5', dur: '4n', vel: 0.1 },
        { note: 'Db5', dur: '8n', vel: 0.16 },
        { note: 'C5', dur: '2n', vel: 0.12 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'F5', dur: '2n', vel: 0.15 },
        { note: 'D5', dur: '4n', vel: 0.12 },
        { note: 'C5', dur: '1n', vel: 0.1 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
      ],
    harmonicaCells: [
      [
        { note: 'F5', dur: '2n', vel: 0.15 },
        { note: 'D5', dur: '4n', vel: 0.12 },
        { note: 'C5', dur: '1n', vel: 0.1 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'G4', dur: '4n', vel: 0.1 },
        { note: 'Bb4', dur: '8n', vel: 0.12 },
        { note: 'C5', dur: '2n', vel: 0.15 },
        null,
        { note: 'F4', dur: '4n', vel: 0.08 },
        { note: 'G4', dur: '1n', vel: 0.1 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        { note: 'D5', dur: '2n', vel: 0.14 },
        null,
        { note: 'C5', dur: '8n', vel: 0.12 },
        { note: 'Bb4', dur: '4n', vel: 0.1 },
        { note: 'G4', dur: '1n', vel: 0.08 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'G4', dur: '8n', vel: 0.11 },
        { note: 'G4', dur: '16n', vel: 0.12 },
        { note: 'Bb4', dur: '16n', vel: 0.13 },
        { note: 'C5', dur: '4n', vel: 0.1 },
        { note: 'Db5', dur: '8n', vel: 0.16 },
        { note: 'C5', dur: '2n', vel: 0.12 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
      ],
      [
        { note: 'D5', dur: '2n', vel: 0.14 },
        null,
        { note: 'C5', dur: '8n', vel: 0.12 },
        { note: 'Bb4', dur: '8n', vel: 0.11 },
        { note: 'A4', dur: '4n', vel: 0.1 },
        { note: 'F4', dur: '4n', vel: 0.09 },
        { note: 'G4', dur: '1n', vel: 0.13 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'G4', dur: '1n', vel: 0.15 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'Bb4', dur: '1n', vel: 0.12 },
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
      ],
      [
        { note: 'G4', dur: '8n', vel: 0.11 },
        { note: 'G4', dur: '16n', vel: 0.12 },
        { note: 'Bb4', dur: '16n', vel: 0.13 },
        { note: 'C5', dur: '8n', vel: 0.14 },
        null,
        { note: 'Db5', dur: '8n', vel: 0.16 },
        { note: 'C5', dur: '8n', vel: 0.12 },
        { note: 'Bb4', dur: '4n', vel: 0.1 },
        { note: 'G4', dur: '2n', vel: 0.09 },
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'F5', dur: '2n', vel: 0.15 },
        { note: 'D5', dur: '4n', vel: 0.12 },
        { note: 'C5', dur: '4n', vel: 0.1 },
        { note: 'Bb4', dur: '1n', vel: 0.08 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        { note: 'G4', dur: '16n', vel: 0.12 },
        { note: 'Bb4', dur: '4n', vel: 0.14 },
        { note: 'G4', dur: '4n', vel: 0.1 },
        { note: 'F4', dur: '8n', vel: 0.09 },
        { note: 'D4', dur: '2n', vel: 0.08 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'G4', dur: '1n', vel: 0.15 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'Bb4', dur: '1n', vel: 0.12 },
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        { note: 'D5', dur: '2n', vel: 0.14 },
        null,
        { note: 'C5', dur: '8n', vel: 0.12 },
        { note: 'Bb4', dur: '8n', vel: 0.11 },
        { note: 'A4', dur: '4n', vel: 0.1 },
        { note: 'F4', dur: '4n', vel: 0.09 },
        { note: 'G4', dur: '1n', vel: 0.13 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'G4', dur: '16n', vel: 0.12 },
        { note: 'Bb4', dur: '4n', vel: 0.14 },
        { note: 'G4', dur: '4n', vel: 0.1 },
        { note: 'F4', dur: '8n', vel: 0.09 },
        { note: 'D4', dur: '2n', vel: 0.08 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
      ],

        ['A5', 'C#6', 'E6'],
      ],

        ['D5', 'F#5', 'A5', 'F#5'],
      ],
      bassNotes:  ['G1', 'D1', 'C1', 'E1', 'D1', 'A1', 'G1', 'B1'],
    },
  }
};