// src/audio/scenes/onboarding.js
//
// "THE ARRIVAL" — A major, 62 BPM
//
// Structured unfolding destiny. Long emotional bends.

export const onboardingScene = {
  bpm: 62,
  transitionTime: 6,
  mood: {
    stringsVol: -30,
    brassVol: -40,
    bassVol: -32,
    percVol: -68,
    reverbWet: 0.65,
    percussionActive: false,
    choirActive: true,
    arpActive: true,
    cyberActive: true,
    melodyActive: true,
    arpDensity: 0.15,
    cyberDensity: 0.2,
    bassIntensity: 0.3,
    melodicMaterial: {
      progressions: [
        [
          { notes: ['A2', 'E3', 'B3'] },     // Asus2
          { notes: ['F#2', 'C#3', 'E3', 'A3'] }, // F#m7
          { notes: ['D3', 'A3', 'E4'] },     // Dadd9
          null,
          { notes: ['E2', 'B2', 'D3', 'G#3'] }, // E7
          { notes: ['C#3', 'G#3', 'B3'] },   // C#m7
          null,
          { notes: ['D3', 'E3', 'A3'] },     // A/D
          { notes: ['F#2', 'A2', 'C#3', 'E3'] },
          { notes: ['B2', 'F#3', 'A3', 'D4'] },
          null,
          { notes: ['E2', 'B2', 'F#3'] },
          { notes: ['A2', 'E3', 'B3'] },
          null,
          { notes: ['D3', 'F#3', 'B3'] },
          { notes: ['E3', 'G#3', 'D4'] },
        ]
      ],
      slideCells: [
      [
        { note: 'G4', dur: '4n', vel: 0.1 },
        { note: 'Bb4', dur: '8n', vel: 0.12 },
        { note: 'C5', dur: '4n', vel: 0.11 },
        { note: 'Db5', dur: '8n', vel: 0.15 },
        { note: 'C5', dur: '2n', vel: 0.1 },
        null,
        null,
        null,
        { note: 'F4', dur: '4n', vel: 0.08 },
        { note: 'G4', dur: '1n', vel: 0.07 },
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'D5', dur: '2n', vel: 0.14 },
        null,
        { note: 'C5', dur: '8n', vel: 0.12 },
        { note: 'Bb4', dur: '8n', vel: 0.11 },
        { note: 'A4', dur: '4n', vel: 0.1 },
        { note: 'F4', dur: '4n', vel: 0.09 },
        { note: 'G4', dur: '1n', vel: 0.13 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        { note: 'G4', dur: '8n', vel: 0.11 },
        { note: 'G4', dur: '16n', vel: 0.12 },
        { note: 'Bb4', dur: '16n', vel: 0.13 },
        { note: 'C5', dur: '8n', vel: 0.14 },
        null,
        { note: 'Db5', dur: '8n', vel: 0.16 },
        { note: 'C5', dur: '8n', vel: 0.12 },
        { note: 'Bb4', dur: '4n', vel: 0.1 },
        { note: 'G4', dur: '2n', vel: 0.09 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'F5', dur: '2n', vel: 0.15 },
        { note: 'D5', dur: '4n', vel: 0.12 },
        { note: 'C5', dur: '4n', vel: 0.1 },
        { note: 'Bb4', dur: '1n', vel: 0.08 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
      ],
    harmonicaCells: [
      [
        { note: 'F5', dur: '2n', vel: 0.15 },
        { note: 'D5', dur: '4n', vel: 0.12 },
        { note: 'C5', dur: '4n', vel: 0.1 },
        { note: 'Bb4', dur: '1n', vel: 0.08 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'G4', dur: '8n', vel: 0.11 },
        { note: 'G4', dur: '16n', vel: 0.12 },
        { note: 'Bb4', dur: '16n', vel: 0.13 },
        { note: 'C5', dur: '8n', vel: 0.14 },
        null,
        { note: 'Db5', dur: '8n', vel: 0.16 },
        { note: 'C5', dur: '8n', vel: 0.12 },
        { note: 'Bb4', dur: '4n', vel: 0.1 },
        { note: 'G4', dur: '2n', vel: 0.09 },
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        { note: 'D5', dur: '2n', vel: 0.14 },
        null,
        { note: 'C5', dur: '8n', vel: 0.12 },
        { note: 'Bb4', dur: '8n', vel: 0.11 },
        { note: 'A4', dur: '4n', vel: 0.1 },
        { note: 'F4', dur: '4n', vel: 0.09 },
        { note: 'G4', dur: '1n', vel: 0.13 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'G4', dur: '4n', vel: 0.1 },
        { note: 'Bb4', dur: '8n', vel: 0.12 },
        { note: 'C5', dur: '4n', vel: 0.11 },
        { note: 'Db5', dur: '8n', vel: 0.15 },
        { note: 'C5', dur: '2n', vel: 0.1 },
        null,
        null,
        null,
        { note: 'F4', dur: '4n', vel: 0.08 },
        { note: 'G4', dur: '1n', vel: 0.07 },
        null,
        null,
        null,
        null,
        null,
        null
      ]
      ],
    starCells: [
        ['A5', 'E6', 'F#6'],
        ['B5', 'E6', 'G#6'],
      ],
      cyberCells: [
        ['A4', 'C#5', 'E5', 'C#5'],
        ['D5', 'F#5', 'A5', 'F#5'],
      ],
      bassNotes:  ['A1', 'E1', 'D1', 'F#1', 'E1', 'C#1', 'B1', 'A1'],
    },
  }
};