// src/audio/scenes/portfolio.js
//
// "THE TRAIL'S END" — G Major, 70 BPM
//
// Reflective structured motifs. Emotional bends on slide.

export const portfolioScene = {
  bpm: 70,
  transitionTime: 4,
  mood: {
    stringsVol: -30,
    brassVol: -40,
    bassVol: -30,
    percVol: -68,
    reverbWet: 0.65,
    percussionActive: false,
    choirActive: true,
    arpActive: true,
    cyberActive: false,
    melodyActive: true,
    arpDensity: 0.2,
    cyberDensity: 0.1,
    bassIntensity: 0.3,
    melodicMaterial: {
      progressions: [
        [
          { notes: ['G2', 'D3', 'A3'] },     // Gsus2
          { notes: ['E2', 'B2', 'D3', 'G3'] }, // Em7
          { notes: ['C3', 'G3', 'D4'] },     // Cadd9
          null,
          { notes: ['D2', 'A2', 'C3', 'F#3'] }, // D7
          { notes: ['B2', 'F#3', 'A3'] },    // Bm7
          null,
          { notes: ['C3', 'D3', 'G3'] },     // G/C
          { notes: ['E2', 'G2', 'B2', 'D3'] },
          { notes: ['A2', 'E3', 'G3'] },
          null,
          { notes: ['D2', 'A2', 'E3'] },
          { notes: ['G2', 'D3', 'A3'] },
          null,
          { notes: ['C3', 'E3', 'A3'] },
          { notes: ['D3', 'F#3', 'C4'] },
        ]
      ],
      slideCells: [
      [
        { note: 'G4', dur: '4n', vel: 0.1 },
        { note: 'Bb4', dur: '8n', vel: 0.12 },
        { note: 'C5', dur: '4n', vel: 0.11 },
        { note: 'Db5', dur: '8n', vel: 0.15 },
        { note: 'C5', dur: '2n', vel: 0.1 },
        null,
        null,
        null,
        { note: 'F4', dur: '4n', vel: 0.08 },
        { note: 'G4', dur: '1n', vel: 0.07 },
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'D5', dur: '2n', vel: 0.14 },
        null,
        { note: 'C5', dur: '8n', vel: 0.12 },
        { note: 'Bb4', dur: '8n', vel: 0.11 },
        { note: 'A4', dur: '4n', vel: 0.1 },
        { note: 'F4', dur: '4n', vel: 0.09 },
        { note: 'G4', dur: '1n', vel: 0.13 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        { note: 'G4', dur: '8n', vel: 0.11 },
        { note: 'G4', dur: '16n', vel: 0.12 },
        { note: 'Bb4', dur: '16n', vel: 0.13 },
        { note: 'C5', dur: '8n', vel: 0.14 },
        null,
        { note: 'Db5', dur: '8n', vel: 0.16 },
        { note: 'C5', dur: '8n', vel: 0.12 },
        { note: 'Bb4', dur: '4n', vel: 0.1 },
        { note: 'G4', dur: '2n', vel: 0.09 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'F5', dur: '2n', vel: 0.15 },
        { note: 'D5', dur: '4n', vel: 0.12 },
        { note: 'C5', dur: '4n', vel: 0.1 },
        { note: 'Bb4', dur: '1n', vel: 0.08 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
      ],
    harmonicaCells: [
      [
        { note: 'F5', dur: '2n', vel: 0.15 },
        { note: 'D5', dur: '4n', vel: 0.12 },
        { note: 'C5', dur: '4n', vel: 0.1 },
        { note: 'Bb4', dur: '1n', vel: 0.08 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'G4', dur: '8n', vel: 0.11 },
        { note: 'G4', dur: '16n', vel: 0.12 },
        { note: 'Bb4', dur: '16n', vel: 0.13 },
        { note: 'C5', dur: '8n', vel: 0.14 },
        null,
        { note: 'Db5', dur: '8n', vel: 0.16 },
        { note: 'C5', dur: '8n', vel: 0.12 },
        { note: 'Bb4', dur: '4n', vel: 0.1 },
        { note: 'G4', dur: '2n', vel: 0.09 },
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        { note: 'D5', dur: '2n', vel: 0.14 },
        null,
        { note: 'C5', dur: '8n', vel: 0.12 },
        { note: 'Bb4', dur: '8n', vel: 0.11 },
        { note: 'A4', dur: '4n', vel: 0.1 },
        { note: 'F4', dur: '4n', vel: 0.09 },
        { note: 'G4', dur: '1n', vel: 0.13 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { note: 'G4', dur: '4n', vel: 0.1 },
        { note: 'Bb4', dur: '8n', vel: 0.12 },
        { note: 'C5', dur: '4n', vel: 0.11 },
        { note: 'Db5', dur: '8n', vel: 0.15 },
        { note: 'C5', dur: '2n', vel: 0.1 },
        null,
        null,
        null,
        { note: 'F4', dur: '4n', vel: 0.08 },
        { note: 'G4', dur: '1n', vel: 0.07 },
        null,
        null,
        null,
        null,
        null,
        null
      ]
      ],
    starCells: [
        ['G5', 'B5', 'D6'],
        ['A5', 'D6', 'E6'],
      ],
      cyberCells: [
        ['G4', 'B4', 'D5', 'B4'],
        ['C5', 'E5', 'G5', 'E5'],
      ],
      bassNotes:  ['G1', 'D1', 'E1', 'C1', 'D1', 'B1', 'A1', 'G1'],
    },
  },
};