/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/halo/Halo`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/halo/HaloArc`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/halo/haloColors`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/halo/HaloOrbit`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/halo/HaloSlice`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/halo/Halo`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/halo/HaloArc`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/halo/haloColors`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/halo/HaloOrbit`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/halo/HaloSlice`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/../src/components/halo/Halo${`?${string}` | `#${string}` | ''}` | `/../src/components/halo/HaloArc${`?${string}` | `#${string}` | ''}` | `/../src/components/halo/haloColors${`?${string}` | `#${string}` | ''}` | `/../src/components/halo/HaloOrbit${`?${string}` | `#${string}` | ''}` | `/../src/components/halo/HaloSlice${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/halo/Halo`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/halo/HaloArc`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/halo/haloColors`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/halo/HaloOrbit`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/halo/HaloSlice`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
