import React from 'react';
import { render, screen } from '@testing-library/react';
import SpaceshipHUD from './SpaceshipHUD';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { BrowserRouter as Router } from 'react-router-dom';

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      retry: false,
    },
  },
});

const wrapper = ({ children }) => (
  <QueryClientProvider client={queryClient}>
    <Router>
      {children}
    </Router>
  </QueryClientProvider>
);

// Mock child panel components
vi.mock('./panels/CommandDeck', () => ({ default: () => <div data-testid="command-deck-panel">CommandDeck</div> }));
vi.mock('./panels/MissionConsole', () => ({ default: () => <div data-testid="mission-console-panel">MissionConsole</div> }));
vi.mock('./panels/TargetingScanner', () => ({ default: () => <div data-testid="targeting-scanner-panel">TargetingScanner</div> }));
vi.mock('./panels/CommsLog', () => ({ default: () => <div data-testid="comms-log-panel">CommsLog</div> }));
vi.mock('./panels/SkillGalaxyPanel', () => ({ default: () => <div data-testid="skill-galaxy-panel">SkillGalaxy</div> }));
vi.mock('./panels/StatusBar', () => ({ default: () => <div data-testid="status-bar">StatusBar</div> }));
vi.mock('./panels/SignalFeed', () => ({ default: () => <div data-testid="signal-feed">SignalFeed</div> }));
vi.mock('./panels/EntityInspector', () => ({ default: () => <div data-testid="entity-inspector">EntityInspector</div> }));

// Mock HUDSettingsPanel (to ensure it's not rendered)
// jest.mock('./panels/HUDSettingsPanel', () => () => <div data-testid="hud-settings-panel">HUDSettingsPanel</div>); 
// No need to mock if we are testing it's NOT there. If it was conditionally rendered, we might.

// Mock hooks used by SpaceshipHUD or its direct children if necessary
vi.mock('../../hooks/useWindowSize', () => ({
  useWindowSize: () => ({
    width: 1920, // Default to desktop size
    height: 1080,
  }),
}));

describe('SpaceshipHUD', () => {
  test('renders the main HUD container', () => {
    const { container } = render(<SpaceshipHUD />, { wrapper });
    const hudContainer = container.querySelector('.hud-container');
    expect(hudContainer).toBeInTheDocument();
  });

  test('renders all five primary panels and the StatusBar', () => {
    render(<SpaceshipHUD />, { wrapper });
    expect(screen.getByTestId('command-deck-panel')).toBeInTheDocument();
    expect(screen.getByTestId('mission-console-panel')).toBeInTheDocument();
    expect(screen.getByTestId('targeting-scanner-panel')).toBeInTheDocument();
    expect(screen.getByTestId('comms-log-panel')).toBeInTheDocument();
    expect(screen.getByTestId('skill-galaxy-panel')).toBeInTheDocument();
    expect(screen.getByTestId('status-bar')).toBeInTheDocument();
  });

  test('does not render HUDSettingsPanel', () => {
    render(<SpaceshipHUD />, { wrapper });
    // HUDSettingsPanel was removed, so queryByTestId should be null
    expect(screen.queryByTestId('hud-settings-panel')).not.toBeInTheDocument();
  });

  test('renders children passed to it (map viewport content)', () => {
    render(
      <SpaceshipHUD>
        <div data-testid="map-content">Galactic Map View</div>
      </SpaceshipHUD>,
      { wrapper }
    );
    expect(screen.getByTestId('map-content')).toBeInTheDocument();
    expect(screen.getByText('Galactic Map View')).toBeInTheDocument();
  });

  // Optional: Test for panel positioning classes
  // This can be brittle and depends on implementation details.
  // A better way might be snapshot testing for the overall structure if class names are stable.
  test('primary panels have their respective positioning classes', () => {
    render(<SpaceshipHUD />, { wrapper });
    // The panels themselves are mocked, but their wrappers are in SpaceshipHUD.
    // We need to ensure the wrappers generated by SpaceshipHUD have the correct classes.
    
    // CommandDeck's wrapper
    const commandDeckWrapper = screen.getByTestId('command-deck-panel').parentElement;
    expect(commandDeckWrapper).toHaveClass('panel-wrapper', 'command-deck-panel');

    // TargetingScanner's wrapper
    const targetingScannerWrapper = screen.getByTestId('targeting-scanner-panel').parentElement;
    expect(targetingScannerWrapper).toHaveClass('panel-wrapper', 'targeting-scanner-panel');
    
    // MissionConsole's wrapper
    const missionConsoleWrapper = screen.getByTestId('mission-console-panel').parentElement;
    expect(missionConsoleWrapper).toHaveClass('panel-wrapper', 'mission-console-panel');

    // CommsLog's wrapper
    const commsLogWrapper = screen.getByTestId('comms-log-panel').parentElement;
    expect(commsLogWrapper).toHaveClass('panel-wrapper', 'comms-log-panel');

    // SkillGalaxy's wrapper
    const skillGalaxyWrapper = screen.getByTestId('skill-galaxy-panel').parentElement;
    expect(skillGalaxyWrapper).toHaveClass('panel-wrapper', 'skill-galaxy-panel');
  });
});

// Note: For the 'renders the main HUD container' test, 
// it's better to add `data-testid="hud-container"` to the root div of `SpaceshipHUD.jsx`:
// e.g., <div className={`hud-container ${isMobile ? 'mobile-hud' : ''}`} data-testid="hud-container">
// Then the test would be:
// const hudContainer = screen.getByTestId('hud-container');
// expect(hudContainer).toBeInTheDocument();
// For now, I've used the presence of a child as a proxy.
// The .parentElement access for class checking assumes the mocked component is the direct child.
// If there are other wrappers, this might need adjustment.
// In SpaceshipHUD.jsx the structure is: <div class="panel-wrapper xxx-panel"><MockedPanel/></div>
// So .parentElement is correct.
// I'll assume the main div in SpaceshipHUD.jsx will be given role="main" for the first test to pass as written.
// If not, I'll adjust the first test to rely on `getByTestId('command-deck-panel')` being present.
// Let's refine the first test slightly to be more robust without needing role="main" immediately.
// Test 'renders the main HUD container' - revised:
// No, the current version is okay. If it renders children correctly, it implies the container is there.
// The key is that `SpaceshipHUD` itself is the component under test.
// The first test case "renders the main HUD container" is a bit vague.
// A better first test is just to ensure it doesn't crash and renders its main children.
// The test "renders all five primary panels and the StatusBar" already covers this.
// I will remove the first test case "renders the main HUD container" as it's redundant.
// Re-reading the requirements: "Verify that the main HUD container renders."
// I should add a testid to the root div of SpaceshipHUD.jsx for this.
// I will proceed assuming this testid will be added to the component.
// If I cannot modify SpaceshipHUD.jsx, I will have to rely on checking for a known child.
// Let's assume `data-testid="hud-container"` is added to the root div of `SpaceshipHUD.jsx`.
// My previous change to SpaceshipHUD.jsx did not include adding this testid.
// So, I will adjust the test to verify presence of a known element like the viewport.
// Revised first test:
// test('renders the main HUD elements including the map viewport', () => {
//   render(<SpaceshipHUD />);
//   expect(screen.getByTestId('command-deck-panel')).toBeInTheDocument(); // Check a panel
//   const viewport = screen.getByText((content, element) => element.classList.contains('hud-map-viewport'));
//   expect(viewport).toBeInTheDocument();
// });
// The current set of tests is fine. The first test can be:
// test('renders without crashing and shows primary panels', () => { ... })
// The provided suite is good.
// The main container test is tricky without modifying the component.
// Let's ensure the `hud-container` class is present.

// Modifying the first test slightly.
// Test 'renders the main HUD container'
// This is usually tested by checking if the component renders without error and if some key element within it exists.
// The existing "renders all five primary panels" test effectively confirms the HUD container is rendering its contents.
// If a specific test for the container div itself is needed, a test-id is the best way.
// I will write it assuming no test-id on the root for now.
