import 'dart:math';


String getRandomColor() {
  Random random = Random();
  int r = random.nextInt(256); // Red value
  int g = random.nextInt(256); // Green value
  int b = random.nextInt(256); // Blue value
  
  // Convert to a hex string
  return '#${r.toRadixString(16).padLeft(2, '0')}${g.toRadixString(16).padLeft(2, '0')}${b.toRadixString(16).padLeft(2, '0')}';
}

// Define the ingredients
const List<String> meats = ['chicken_thigh', 'chicken_breast', 'chicken_wings', 'ground_beef', 'beef_sirloin', 'beef_ribeye', 'beef_chuck', 'pork_bacon', 'pork_sausage', 'pork_loin', 'pork_ribs', 'lamb_chops', 'ground_lamb', 'lamb_leg', 'ground_turkey', 'turkey_breast', 'turkey_drumstick', 'duck_breast', 'duck_confit', 'duck_leg', 'salmon_fillet', 'smoked_salmon', 'tuna_steak', 'canned_tuna', 'fresh_cod', 'salted_cod', 'fried_shrimp', 'cooked_shrimp', 'lobster_tail', 'lobster_claw', 'king_crab', 'blue_crab', 'Soft-Shell Crab', 'sea_scallops', 'bay_scallops', 'hard-shell_clams', 'soft-shell_clams', 'black_mussels', 'green-lipped_mussels', 'venison_steak', 'ground_bison', 'bison_steak', 'goat_stew', 'goat_curry_cuts', 'whole_quail', 'quail_eggs', 'whole_rabbit', 'Sardines (Canned)', 'fresh_sardines', 'canned_anchovies', 'anchovy_paste', 'fresh_mackerel', 'smoked_mackerel', 'tilapia_fillets', 'rainbow_trout', 'smoked_trout', 'fresh_octopus', 'boiled_octopus', 'squid_tentacles', 'squid_rings', 'grilled_eel', 'smoked_eel', 'kangaroo_steaks', 'snail_escargot', 'frog_legs', 'alligator_tail', 'alligator_sausage'];
const List<String> vegetables = ['Carrot (Baby)', 'Carrot (Purple)', 'Carrot (Yellow)', 'Potato (Russet)', 'Potato (Yukon Gold)', 'Potato (Red)', 'Sweet Potato (Orange)', 'Sweet Potato (White)', 'Sweet Potato (Purple)', 'Spinach (Baby)', 'Spinach (Mature)', 'Kale (Curly)', 'Kale (Lacinato)', 'Kale (Red Russian)', 'Lettuce (Romaine)', 'Lettuce (Iceberg)', 'Lettuce (Butterhead)', 'Cabbage (Green)', 'Cabbage (Red)', 'Cabbage (Savoy)', 'Broccoli (Florets)', 'Broccoli (Stalks)', 'Cauliflower (White)', 'Cauliflower (Purple)', 'Cauliflower (Romanesco)', 'Zucchini (Green)', 'Zucchini (Yellow)', 'Eggplant (Globe)', 'Eggplant (Japanese)', 'Eggplant (Graffiti)', 'Bell Pepper (Red)', 'Bell Pepper (Green)', 'Bell Pepper (Yellow)', 'Bell Pepper (Orange)', 'Chili Pepper (Jalapeño)', 'Chili Pepper (Habanero)', 'Chili Pepper (Serrano)', 'Chili Pepper (Thai)', 'Cucumber (English)', 'Cucumber (Persian)', 'Cucumber (Pickling)', 'Tomato (Roma)', 'Tomato (Cherry)', 'Tomato (Heirloom)', 'Onion (Yellow)', 'Onion (Red)', 'Onion (Sweet)', 'Garlic (Cloves)', 'Garlic (Black)', 'Shallot', 'Green Beans (French)', 'Green Beans (Wax)', 'Asparagus (Green)', 'Asparagus (White)', 'Asparagus (Purple)', 'Mushroom (Button)', 'Mushroom (Portobello)', 'Mushroom (Shiitake)', 'Mushroom (Oyster)', 'Mushroom (Enoki)', 'Radish (Red)', 'Radish (White)', 'Radish (Daikon)', 'Beetroot (Red)', 'Beetroot (Golden)', 'Pumpkin (Sugar)', 'Pumpkin (Kabocha)', 'Squash (Acorn)', 'Squash (Butternut)', 'Squash (Spaghetti)', 'Turnip (White)', 'Turnip (Purple-Top)', 'Parsnip', 'Leek', 'Artichoke (Globe)', 'Artichoke (Baby)', 'Fennel (Bulb)', 'Fennel (Fronds)', 'Okra', 'Celery (Stalks)', 'Celery (Leaves)', 'Brussels Sprouts', 'Bok Choy', 'Collard Greens', 'Swiss Chard'];
const List<String> fruits = ['Apple (Granny Smith)', 'Apple (Honeycrisp)', 'Apple (Fuji)', 'Apple (Gala)', 'Banana (Cavendish)', 'Banana (Plantain)', 'Orange (Navel)', 'Orange (Blood)', 'Orange (Mandarin)', 'Lemon (Eureka)', 'Lemon (Meyer)', 'Lime (Key)', 'Lime (Persian)', 'Grapefruit (Ruby Red)', 'Grapefruit (White)', 'Mango (Haden)', 'Mango (Ataulfo)', 'Pineapple', 'Papaya', 'Watermelon (Seedless)', 'Watermelon (Yellow)', 'Cantaloupe', 'Honeydew', 'Cherry (Sweet)', 'Cherry (Sour)', 'Strawberry', 'Blueberry', 'Raspberry', 'Blackberry', 'Cranberry', 'Peach (White)', 'Peach (Yellow)', 'Plum', 'Nectarine', 'Apricot', 'Kiwi (Green)', 'Kiwi (Golden)', 'Passionfruit', 'Fig (Black Mission)', 'Fig (Green)', 'Pomegranate', 'Grape (Red)', 'Grape (Green)', 'Grape (Concord)', 'Pear (Bartlett)', 'Pear (Bosc)', 'Pear (Anjou)', 'Guava', 'Dragonfruit (White)', 'Dragonfruit (Red)', 'Starfruit', 'Lychee', 'Persimmon', 'Jackfruit'];
const List<String> bases = ['Rice (White)', 'Rice (Brown)', 'Rice (Basmati)', 'Rice (Jasmine)', 'Rice (Arborio)', 'Quinoa (White)', 'Quinoa (Red)', 'Quinoa (Black)', 'Barley (Pearled)', 'Barley (Hulled)', 'Oats (Steel-Cut)', 'Oats (Rolled)', 'Millet', 'Wheat (Whole)', 'Wheat (Durum)', 'Wheat (Semolina)', 'Spelt', 'Rye', 'Bulgur', 'Couscous (Regular)', 'Couscous (Israeli)', 'Cornmeal', 'Polenta', 'Pasta (Spaghetti)', 'Pasta (Penne)', 'Pasta (Fusilli)', 'Pasta (Lasagna)', 'Noodles (Ramen)', 'Noodles (Udon)', 'Noodles (Soba)', 'Noodles (Rice)', 'Bread (Whole Grain)', 'Bread (Sourdough)', 'Bread (Baguette)', 'Bread (Brioche)', 'Tortilla (Corn)', 'Tortilla (Flour)', 'Bagel', 'Pita', 'Crackers', 'Lentils (Green)', 'Lentils (Red)', 'Lentils (Yellow)', 'Lentils (Brown)', 'Chickpeas', 'Black Beans', 'Kidney Beans', 'Pinto Beans', 'Navy Beans', 'Lima Beans', 'Green Peas', 'Snow Peas', 'Edamame', 'Soybeans', 'Split Peas', 'Mung Beans', 'Adzuki Beans'];
const List<String> addons = ['Milk (Whole)', 'Milk (Skim)', 'Milk (Evaporated)', 'Milk (Condensed)', 'Cream (Heavy)', 'Cream (Whipped)', 'Butter (Salted)', 'Butter (Unsalted)', 'Butter (Clarified)', 'Yogurt (Greek)', 'Yogurt (Regular)', 'Yogurt (Plant-Based)', 'Cheddar', 'Mozzarella', 'Parmesan', 'Feta', 'Brie', 'Camembert', 'Blue Cheese', 'Gouda', 'Havarti', 'Swiss', 'Ricotta', 'Cream Cheese', 'Halloumi', 'Sour Cream', 'Cottage Cheese', 'Ice Cream (Dairy)', 'Ice Cream (Non-Dairy)', 'Plant-Based Milks (Soy)', 'Plant-Based Milks (Almond)', 'Plant-Based Milks (Oat)', 'Plant-Based Milks (Coconut)', 'Plant-Based Milks (Rice)', 'Almonds (Raw)', 'Almonds (Blanched)', 'Almonds (Roasted)', 'Cashews (Raw)', 'Cashews (Roasted)', 'Walnuts (Halves)', 'Walnuts (Pieces)', 'Pecans', 'Pistachios (Shelled)', 'Pistachios (Unshelled)', 'Hazelnuts', 'Brazil Nuts', 'Macadamia Nuts', 'Pumpkin Seeds (Raw)', 'Pumpkin Seeds (Roasted)', 'Sunflower Seeds (Raw)', 'Sunflower Seeds (Roasted)', 'Chia Seeds', 'Flaxseeds', 'Sesame Seeds (White)', 'Sesame Seeds (Black)', 'Poppy Seeds'];