name: Build and Push Docker Images
on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and Push User Management Image
        run: |
          docker build -t myrepo/user-management ./user-management
          docker push myrepo/user-management
      - name: Build and Push Project Management Image
        run: |
          docker build -t myrepo/project-management ./project-management
          docker push myrepo/project-management
